//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSAILORRandomisation.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    
    public partial class SAILORTest
    {
        public int RandID { get; set; }
        public string SiteID { get; set; }


        [Required]
        public Nullable<int> ScreeningID { get; set; }

        [Required]
        [StringLength(3)]
        [RegularExpression("^[A-Z ]*$", ErrorMessage = "Please enter capital letters")]
        public string ParticipantInitials { get; set; }


        [Required]
        [Range(18, 150, ErrorMessage ="Participant must be over 18 years old.")]
        public Nullable<int> Age { get; set; }


        public Nullable<int> Gender { get; set; }
        public string SITE { get; set; }
        public string RandomisedBy { get; set; }



        [Required]
        [Range(0, 1, ErrorMessage = "Inclusion criteria must be met.")]
        public Nullable<int> Incl { get; set; }

        [Required]
        [Range(2, 3, ErrorMessage = "Exclusion criteria is not met.")]
        public Nullable<int> Excl { get; set; }


        [Required]
        [Range(0, 1, ErrorMessage = "Inclusion criteria must be met.")]
        public Nullable<int> ApproveMedical { get; set; }

        [Required]
        [DataType(DataType.Date)]
        //  [DisplayFormat(DataFormatString = "{(3[01]|[12]\d|0[1-9])/(0[13578]|10|12)/((?!0000)\d{4})|(30|[12]\d|0[1-9])/(0[469]|11)/((?!0000)\d{4})|(2[0-8]|[01]\d|0[1-9])/(02)/((?!0000)\d{4})|29/(02)/(1600|2000|2400|2800|00)|29/(02)/(\d\d)(0[48]|[2468][048]|[13579][26])}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ConsentDate { get; set; }


        public Nullable<System.DateTime> RandDate { get; set; }
        public Nullable<System.DateTime> RandTime { get; set; }
        public string RandAllocation { get; set; }
        public Nullable<int> RandMethod { get; set; }
        public Nullable<int> RandError { get; set; }
        public Nullable<System.DateTime> RandErrorDate { get; set; }
    }
}





